# Utilise une image officielle légère avec Python
FROM python:3.10-slim

# Définir le dossier de travail
WORKDIR /app

# Mettre à jour et installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    poppler-utils \
    tesseract-ocr \
    libgl1 \
    wget \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copier les fichiers de l'application
COPY . /app

# Copier et installer les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port si tu utilises FastAPI en HTTP
EXPOSE 8001

# Commande de démarrage
CMD ["python", "main_v2.py"]
