# Configuration de l'application
spring.application.name=Employee-Module
  server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Configuration DB
spring.datasource.url=jdbc:postgresql://localhost:5433/looyas-pfe
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.tomcat.test-on-borrow=true
spring.datasource.tomcat.validation-query=SELECT 1


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Email (conservez votre configuratiInterviewServiceon existante)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= bizertinmustapha@gmail.com
spring.mail.password= yfrlrsiugiwxmbhf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.ssl.trust=*

# JWT (conservez votre configuration existante)
jwt.expiration=19000000
jwt.secret=your-256-bit-secret-key-must-be-at-least-32-bytes-long
# etape
# URL du REST API Camunda
camunda.rest-url=http://localhost:8080/engine-rest

# Cl� de votre process BPMN
camunda.process.key=Workflow_Conge

# D�finitions des tasks (identifiants dans le BPMN)
camunda.task.manager=UserTask_ValidationManager
camunda.task.rh=UserTask_ValidationRH

# Groupes candidats
camunda.group.manager=managers
camunda.group.rh=rh

# Topics External Task
camunda.topic.rejection=send-rejection-email
camunda.topic.final-approval=send-final-approval-email


# Squence de vos userTask Ids tels qu?ils apparaissent dans le BPMN
camunda.task.keys=UserTask_ValidationManager,UserTask_ValidationRH

# Cls de variables  remplir pour chaque tache
camunda.task.decision-keys=decisionManager,decisionRH
camunda.task.comment-keys=commentaireManager,commentaireRH

# Statuts  appliquer quand on approuve / rejette (mmes longueurs que ci-dessus)
camunda.task.approve-statuses=Validated by Manager,Validated by HR
camunda.task.reject-statuses=Rejected by Manager,Rejected by HR
# Quand la tache Manager est approuvee, quel status mettre ?
# Puis le meme pour RH.
# calcule de salaire
fastapi.url=http://localhost:8000/predict

salaire.cnss.rate=0.0918
salaire.deduction.forfaitaire.max=2000.0
salaire.deduction.forfaitaire.percent=0.10

# RabbitMq.
spring.rabbitmq.host=localhost
#spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#nlp.api.url=http://nlp-api:8000
nlp.api.url=http://localhost:8000

messages.folder.path=C:/Users/Fatma/OneDrive/Bureau/microservice-dockerise/HR-Platform/message-model/data

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#RabbitMQ Training


rabbitmq.training-recommendation.queue=training-recommendation-request-queue
rabbitmq.training-recommendation.exchange=training-recommendation-exchange
rabbitmq.training-recommendation.routingkey=training-recommendation-request

rabbitmq.training-recommendation.response-queue=training-recommendation-response-queue

# Career Pathing Rabbit Mq

rabbitmq.career-pathing.queue=career-pathing-request-queue
rabbitmq.career-pathing.exchange=career-pathing-exchange
rabbitmq.career-pathing.routing-key=career-pathing.routing.key

# File de reponse Career Pathing
rabbitmq.career-pathing.response-queue=career-pathing-response-queue