import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { Box, Typography, Paper, Button, CircularProgress } from '@mui/material';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const PayslipDetailPage = () => {
  const { id } = useParams();
  const [payslip, setPayslip] = useState(null);
  const [employee, setEmployee] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    fetchPayslip();
  }, []);
const API_URL = process.env.REACT_APP_API_URL; 
 
console.log('API_URL:', API_URL);
  const fetchPayslip = async () => {
    try {
      const token = localStorage.getItem('accessToken')?.replace(/"/g, '') || '';
      const config = { headers: { Authorization: `Bearer ${token}` } };

      // Fetch payslip details
      const payslipResponse = await axios.get(`${API_URL}/payslips/${id}`, config);
      setPayslip(payslipResponse.data);
      console.log(payslipResponse.data);

      // Fetch employee details
      try {
        const employeeResponse = await axios.get(`${API_URL}/employee/${payslipResponse.data.userId}`, config);
        setEmployee(employeeResponse.data);
        console.log('Employee details fetched:', employeeResponse.data);
      } catch (error) {
        console.warn('Error fetching employee details:', error);
        setEmployee({ firstname: 'Unknown', lastname: '', department: { name: 'N/A' }, jobTitle: 'N/A', seniority: 'N/A' });
      }
    } catch (error) {
      console.error('Error fetching payslip:', error);
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = (payslip, employee) => {
    const doc = new jsPDF();

    const safe = (val, decimals = 2) => {
      return typeof val === 'number' ? val.toFixed(decimals) : '0.00';
    };

    const formatDate = (dateString) => {
      if (!dateString) return 'N/A';
      const date = new Date(dateString);
      return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
    };

    // Title
    doc.setFontSize(18);
    doc.text('PAYSLIP', 105, 15, { align: 'center' });

    // Employee Info
    doc.setFontSize(11);
        doc.text(`Payslip ID: ${payslip?.payslipId || 'N/A'}`, 14, 66);
    doc.text(`Payslip ID: ${employee?.payslipId || 'N/A'}`, 14, 66);

    doc.text(`Employee: ${employee?.firstname || 'Unknown'} ${employee?.lastname || ''}`, 14, 30);
    doc.text(`Department: ${employee?.departmentName || employee?.department || 'N/A'}`, 14, 36);
    doc.text(`Job Title: ${employee?.jobTitle || 'N/A'}`, 14, 42);
    doc.text(`Seniority: ${employee?.seniority || 'N/A'}`, 14, 54);
    doc.text(`Period: ${formatDate(payslip?.startDate)} - ${formatDate(payslip?.date)}`, 14, 60);
    doc.text(`Payslip ID: ${payslip?.payslipId }`, 14, 66);

    // Salary Table
    autoTable(doc, {
      startY: 74,
      head: [['Element', 'Presence', 'Amount']],
      body: [
        ['Base Salary', `${safe(payslip?.presentDays)} days`, `${safe(payslip?.baseSalary)} DT`],
        ['Gross Salary', '', `${safe(payslip?.grossSalary)} DT`]
      ],
      styles: { fontSize: 9 },
      headStyles: { fillColor: [22, 160, 133], textColor: 255 }
    });

    // Contributions
    const cotisationRows = [
      ['CNSS', `${safe(payslip?.grossSalary)} DT`, `${safe(payslip?.cnssDeduction / (payslip?.grossSalary || 1) * 100, 2)}%`, `${safe(payslip?.cnssDeduction)} DT`],
      ['IRPP', `${safe(payslip?.grossSalary)} DT`, `${safe(payslip?.irppDeduction / (payslip?.grossSalary || 1) * 100, 2)}%`, `${safe(payslip?.irppDeduction)} DT`]
    ];

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 5,
      head: [['Contribution', 'Base', 'Rate', 'Deduction']],
      body: cotisationRows,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255 }
    });

    // Summary
    const gross = payslip?.grossSalary || 0;
    const absenceDeduction = payslip?.absenceDeduction || 0;
    const deductions = payslip?.deductions || 0;
    const netAvantImpots = gross - deductions;
    const netFinal = payslip?.netSalary || netAvantImpots;

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      body: [
        ['Absence Deduction', '', '', `${safe(absenceDeduction)} DT`],
        ['Total Deductions (CNSS + IRPP)', '', '', `${safe(deductions)} DT`],
        ['Net Before Tax', '', '', `${safe(netAvantImpots)} DT`],
        ['Net Paid', '', '', `${safe(netFinal)} DT`]
      ],
      styles: { fontSize: 10, fontStyle: 'bold' },
      columnStyles: { 3: { halign: 'right' } }
    });

    // Footer
    doc.setFontSize(9);
    doc.text('Document generated by HR Platform', 14, 290);

    doc.save(
      `Payslip_${employee?.firstname || 'Employee'}_${employee?.lastname || 'Unknown'}_${new Date(payslip?.date).toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' }).replace(/\//g, '-')}.pdf`
    );
  };

  if (loading) {
    return <Box display="flex" justifyContent="center" mt={5}><CircularProgress size={60} /></Box>;
  }

  if (!payslip) {
    return <Typography align="center" color="error">Payslip not found.</Typography>;
  }

  return (
    <Paper elevation={3} sx={{ p: 5, maxWidth: 800, mx: 'auto', mt: 5 }}>
      <Typography variant="h4" fontWeight="bold" gutterBottom>
        Payslip Details
      </Typography>

      <Typography>ID: {payslip.payslipId}</Typography>
      <Typography>From: {new Date(payslip.startDate).toLocaleDateString()}</Typography>
      <Typography>To: {new Date(payslip.date).toLocaleDateString()}</Typography>
      {employee && (
        <>
          <Typography>Employee: {employee.firstname} {employee.lastname}</Typography>
          <Typography>Department: {employee.departmentName || 'N/A'}</Typography>
          <Typography>Job Title: {employee.jobTitle || 'N/A'}</Typography>
          <Typography>Seniority: {employee.seniority || 'N/A'}</Typography>
        </>
      )}
      <Typography>Absence Days: {payslip.unjustifiedAbsences || 0}</Typography>
      <Typography>Base Salary: {payslip.baseSalary.toFixed(2)} DT</Typography>
      <Typography>Deductions: {payslip.deductions.toFixed(2)} DT</Typography>
      <Typography>Net Salary: {payslip.netSalary.toFixed(2)} DT</Typography>

      <Box mt={4}>
        <Button variant="contained" color="primary" onClick={() => generatePDF(payslip, employee)}>
          Generate PDF
        </Button>
      </Box>
    </Paper>
  );
};

export default PayslipDetailPage;