server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA: renvoie vers index.html quand l’URL n’existe pas côté serveur
  location / {
    try_files $uri /index.html;
  }

  # (Optionnel) Proxy vers ton backend si tu appelles /api/* depuis le front
  # Remplace "gateway:8080" par le nom/port de ton service backend dans le réseau Docker
  location /api/ {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass http://gateway-service:8888/;  # le / final enlève le préfixe /api
}
# location / { try_files $uri /index.html; }


  # Healthcheck
  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  # Gzip basique
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
