--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analyse_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analyse_message (
    id bigint NOT NULL,
    emotion character varying(255),
    message character varying(255),
    sentiment character varying(255),
    topic character varying(255),
    message_result_id bigint
);


ALTER TABLE public.analyse_message OWNER TO postgres;

--
-- Name: analyse_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analyse_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyse_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analysis_result (
    id bigint NOT NULL,
    adjusted_satisfaction double precision NOT NULL,
    analyzed_at timestamp(6) without time zone,
    dissatisfaction_causes character varying(1000),
    dissatisfaction_score double precision NOT NULL,
    employee_id bigint NOT NULL,
    global_satisfaction double precision NOT NULL,
    questionnaire_id bigint NOT NULL,
    satisfaction_causes character varying(1000),
    neutral_causes character varying(1000)
);


ALTER TABLE public.analysis_result OWNER TO postgres;

--
-- Name: analysis_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analysis_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answer (
    id bigint NOT NULL,
    response_text character varying(255),
    employe_id bigint,
    question_id bigint,
    questionnaire_id bigint
);


ALTER TABLE public.answer OWNER TO postgres;

--
-- Name: answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    dtype character varying(31) NOT NULL,
    id bigint NOT NULL,
    cin character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    reset_token character varying(255),
    role character varying(255),
    token_expiration timestamp(6) without time zone,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['RH'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying, 'EMPLOYEE'::character varying])::text[])))
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.application (
    application_id bigint NOT NULL,
    application_date date,
    application_status character varying(255),
    cv_file oid,
    email character varying(255) NOT NULL,
    mobile_phone character varying(255),
    job_offer_id bigint,
    name character varying(255) NOT NULL,
    match_id bigint,
    resume_id bigint,
    spontaneous_job_title character varying(255)
);


ALTER TABLE public.application OWNER TO postgres;

--
-- Name: application_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.application ALTER COLUMN application_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_path_need_company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_path_need_company (
    id bigint NOT NULL,
    career_path_name character varying(255)
);


ALTER TABLE public.career_path_need_company OWNER TO postgres;

--
-- Name: career_path_need_company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_path_need_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_path_need_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_pathing_recommendation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_pathing_recommendation (
    id bigint NOT NULL,
    from_company_needs boolean,
    justification text,
    match_percentage integer,
    title character varying(255),
    employee_id bigint
);


ALTER TABLE public.career_pathing_recommendation OWNER TO postgres;

--
-- Name: career_pathing_recommendation_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_pathing_recommendation_employee (
    id bigint NOT NULL,
    employee_id bigint,
    recommendation_id bigint
);


ALTER TABLE public.career_pathing_recommendation_employee OWNER TO postgres;

--
-- Name: career_pathing_recommendation_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_pathing_recommendation_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_pathing_recommendation_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_pathing_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_pathing_recommendation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_pathing_recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_pathing_recommendation_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_pathing_recommendation_plan (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255),
    requester_id bigint
);


ALTER TABLE public.career_pathing_recommendation_plan OWNER TO postgres;

--
-- Name: career_pathing_recommendation_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_pathing_recommendation_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_pathing_recommendation_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_pathing_skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.career_pathing_skill (
    id bigint NOT NULL,
    is_existing_skill boolean,
    related_skill_name character varying(255),
    job_id bigint NOT NULL
);


ALTER TABLE public.career_pathing_skill OWNER TO postgres;

--
-- Name: career_pathing_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.career_pathing_skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_pathing_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certification (
    certification_id bigint NOT NULL,
    date character varying(255),
    certification_name character varying(100) NOT NULL,
    resume_id bigint NOT NULL
);


ALTER TABLE public.certification OWNER TO postgres;

--
-- Name: certification_certification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certification ALTER COLUMN certification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certification_certification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.channel (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.channel OWNER TO postgres;

--
-- Name: channel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: choice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.choice (
    id bigint NOT NULL,
    text character varying(255),
    question_id bigint
);


ALTER TABLE public.choice OWNER TO postgres;

--
-- Name: choice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.choice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.choice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    client_id bigint NOT NULL,
    address character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255)
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coaching_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coaching_session (
    id bigint NOT NULL,
    coach_justification text,
    priority character varying(255),
    priority_justification text,
    skills_justification text,
    training_justification text,
    training_title character varying(255),
    coach_id bigint,
    training_recommendation_plan_id bigint
);


ALTER TABLE public.coaching_session OWNER TO postgres;

--
-- Name: coaching_session_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coaching_session_employee (
    coaching_session_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.coaching_session_employee OWNER TO postgres;

--
-- Name: coaching_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.coaching_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coaching_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    comment_id bigint NOT NULL,
    content character varying(1000),
    created_date timestamp(6) without time zone,
    author_id bigint,
    task_id bigint
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- Name: comment_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contract_type (
    id bigint NOT NULL,
    contract_type_name character varying(255)
);


ALTER TABLE public.contract_type OWNER TO postgres;

--
-- Name: contract_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contract_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id_currency bigint NOT NULL,
    currency_name character varying(255)
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- Name: currency_id_currency_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id_currency ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_currency_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    department_name character varying(255) NOT NULL
);


ALTER TABLE public.department OWNER TO postgres;

--
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diploma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diploma (
    id_diplome integer NOT NULL,
    diploma_year character varying(255),
    diplome_type character varying(255),
    institution character varying(255),
    speciality character varying(255),
    employe_id bigint
);


ALTER TABLE public.diploma OWNER TO postgres;

--
-- Name: diploma_id_diplome_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diploma ALTER COLUMN id_diplome ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diploma_id_diplome_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diploma_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diploma_type (
    id_diploma_type bigint NOT NULL,
    diploma_name character varying(255),
    specialty character varying(255),
    speciality character varying(255)
);


ALTER TABLE public.diploma_type OWNER TO postgres;

--
-- Name: diploma_type_id_diploma_type_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diploma_type ALTER COLUMN id_diploma_type ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diploma_type_id_diploma_type_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: education; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.education (
    education_id bigint NOT NULL,
    degree character varying(255) NOT NULL,
    end_date character varying(255),
    institution character varying(255) NOT NULL,
    start_date character varying(255),
    resume_id bigint NOT NULL
);


ALTER TABLE public.education OWNER TO postgres;

--
-- Name: education_education_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.education ALTER COLUMN education_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.education_education_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employe (
    address character varying(255),
    bank_account_number character varying(255),
    birth_date timestamp(6) without time zone,
    birth_place character varying(255),
    gender character varying(255),
    job_title character varying(255),
    martial_status character varying(255),
    mobile_phone character varying(255),
    nationality character varying(255),
    number_of_children integer NOT NULL,
    personal_address character varying(255),
    personal_phone character varying(255),
    policy_number_ins character varying(255),
    professionalemail character varying(255),
    salary integer NOT NULL,
    seniority character varying(255),
    social_security_code character varying(255),
    workplace character varying(255),
    worktime character varying(255),
    id bigint NOT NULL,
    contract_type_id bigint,
    department_id bigint,
    parent_id bigint,
    manager_id bigint,
    hire_date timestamp(6) without time zone,
    insurance_group_id bigint,
    other_information_id bigint,
    reset_status character varying(255),
    CONSTRAINT employe_gender_check CHECK (((gender)::text = ANY ((ARRAY['FEMALE'::character varying, 'MALE'::character varying])::text[]))),
    CONSTRAINT employe_martial_status_check CHECK (((martial_status)::text = ANY ((ARRAY['SINGLE'::character varying, 'MARRIED'::character varying, 'DIVORCED'::character varying])::text[]))),
    CONSTRAINT employe_reset_status_check CHECK (((reset_status)::text = ANY ((ARRAY['NONE'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT employe_seniority_check CHECK (((seniority)::text = ANY ((ARRAY['BEGINNER'::character varying, 'MIDJUNIOR'::character varying, 'JUNIOR'::character varying, 'SENIOR'::character varying])::text[]))),
    CONSTRAINT employe_worktime_check CHECK (((worktime)::text = ANY ((ARRAY['H48'::character varying, 'H40'::character varying, 'MATERNITY'::character varying])::text[])))
);


ALTER TABLE public.employe OWNER TO postgres;

--
-- Name: employee_insight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_insight (
    employee_insight_id bigint NOT NULL,
    centrality real,
    contact_count real,
    discussion_id integer,
    dominant_sentiment character varying(255),
    extracted_topics character varying(255),
    global_classification character varying(255),
    intensity_score real,
    isolation_flag boolean,
    no_message integer,
    period_end timestamp(6) without time zone,
    period_start timestamp(6) without time zone,
    risk_flag boolean,
    risk_type character varying(255),
    tone character varying(255),
    user_id bigint
);


ALTER TABLE public.employee_insight OWNER TO postgres;

--
-- Name: employee_insight_employee_insight_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_insight ALTER COLUMN employee_insight_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_insight_employee_insight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_skills; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_skills (
    id bigint NOT NULL,
    current_level integer NOT NULL,
    name character varying(255),
    target_level integer NOT NULL,
    employe_id bigint
);


ALTER TABLE public.employee_skills OWNER TO postgres;

--
-- Name: employee_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experience; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experience (
    experience_id bigint NOT NULL,
    company character varying(255) NOT NULL,
    description text,
    end_date character varying(255),
    start_date character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255),
    resume_id bigint NOT NULL
);


ALTER TABLE public.experience OWNER TO postgres;

--
-- Name: experience_experience_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.experience ALTER COLUMN experience_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experience_experience_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: global_insight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.global_insight (
    global_insight_id bigint NOT NULL,
    discussion_id integer,
    dominant_sentiment character varying(255),
    extracted_topics character varying(255),
    global_classification character varying(255),
    intensity_score real,
    neg real,
    neutral real,
    no_message integer,
    period_end timestamp(6) without time zone,
    period_start timestamp(6) without time zone,
    pos real,
    risk_flag boolean,
    risk_type character varying(255)
);


ALTER TABLE public.global_insight OWNER TO postgres;

--
-- Name: global_insight_employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.global_insight_employees (
    global_insight_global_insight_id bigint NOT NULL,
    employees_employee_insight_id bigint NOT NULL
);


ALTER TABLE public.global_insight_employees OWNER TO postgres;

--
-- Name: global_insight_global_insight_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.global_insight ALTER COLUMN global_insight_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.global_insight_global_insight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: history_workflow_leave; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.history_workflow_leave (
    history_workflow_leave_id bigint NOT NULL,
    comment character varying(1024),
    completed_at character varying(255),
    decision character varying(255),
    leave_end_date character varying(255),
    leave_start_date character varying(255),
    leave_type character varying(255),
    pro_inst_id character varying(255),
    requester_firstname character varying(255),
    requester_id bigint,
    requester_lastname character varying(255),
    task_id character varying(255),
    task_name character varying(255),
    employee_id bigint
);


ALTER TABLE public.history_workflow_leave OWNER TO postgres;

--
-- Name: history_workflow_leave_history_workflow_leave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.history_workflow_leave ALTER COLUMN history_workflow_leave_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.history_workflow_leave_history_workflow_leave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imputation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imputation (
    imputation_id bigint NOT NULL,
    date character varying(255),
    end_time time(6) without time zone,
    hours integer NOT NULL,
    started_time time(6) without time zone,
    total_hours integer NOT NULL,
    user_id bigint,
    task_id bigint,
    description character varying(255),
    is_draft boolean,
    validee boolean,
    payslip_id bigint,
    project_id bigint
);


ALTER TABLE public.imputation OWNER TO postgres;

--
-- Name: imputation_imputation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imputation ALTER COLUMN imputation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imputation_imputation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: included_skill_coaching; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.included_skill_coaching (
    coaching_session_id bigint NOT NULL,
    included_skill_name character varying(255)
);


ALTER TABLE public.included_skill_coaching OWNER TO postgres;

--
-- Name: included_skill_self_training; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.included_skill_self_training (
    self_training_session_id bigint NOT NULL,
    included_skill_name character varying(255)
);


ALTER TABLE public.included_skill_self_training OWNER TO postgres;

--
-- Name: included_skill_structured_training; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.included_skill_structured_training (
    structured_training_session_id bigint NOT NULL,
    included_skill_name character varying(255)
);


ALTER TABLE public.included_skill_structured_training OWNER TO postgres;

--
-- Name: insurance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.insurance (
    id bigint NOT NULL,
    contact_info character varying(255),
    description character varying(255),
    end_date date,
    insurance_provider character varying(255),
    name character varying(255),
    start_date date
);


ALTER TABLE public.insurance OWNER TO postgres;

--
-- Name: insurance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.insurance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insurance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview (
    interview_id bigint NOT NULL,
    duration integer NOT NULL,
    location character varying(255),
    meeting_link character varying(255),
    scheduled_date_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    application_id bigint NOT NULL,
    room_id bigint
);


ALTER TABLE public.interview OWNER TO postgres;

--
-- Name: interview_interview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interview ALTER COLUMN interview_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_interview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_interviewers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interview_interviewers (
    interview_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.interview_interviewers OWNER TO postgres;

--
-- Name: language; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.language (
    language_id bigint NOT NULL,
    level character varying(255),
    language character varying(255),
    resume_id bigint NOT NULL
);


ALTER TABLE public.language OWNER TO postgres;

--
-- Name: language_language_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.language ALTER COLUMN language_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.language_language_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_request (
    id bigint NOT NULL,
    approver_id bigint,
    description character varying(500),
    end_date character varying(255) NOT NULL,
    request_date character varying(255),
    start_date character varying(255) NOT NULL,
    status character varying(255),
    employee_id bigint,
    leave_type bigint,
    workflow_leave_id bigint,
    number_of_hours double precision
);


ALTER TABLE public.leave_request OWNER TO postgres;

--
-- Name: leave_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_sold; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_sold (
    id_leave_sold integer NOT NULL,
    solde double precision NOT NULL,
    employe_id bigint,
    leave_type_id bigint NOT NULL
);


ALTER TABLE public.leave_sold OWNER TO postgres;

--
-- Name: leave_sold_id_leave_sold_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_sold ALTER COLUMN id_leave_sold ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_sold_id_leave_sold_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leave_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_type (
    id_leave_type bigint NOT NULL,
    solde integer,
    type character varying(255) NOT NULL
);


ALTER TABLE public.leave_type OWNER TO postgres;

--
-- Name: leave_type_id_leave_type_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_type ALTER COLUMN id_leave_type ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_type_id_leave_type_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: link; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.link (
    link_id bigint NOT NULL,
    link character varying(500) NOT NULL,
    resume_id bigint NOT NULL
);


ALTER TABLE public.link OWNER TO postgres;

--
-- Name: link_link_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.link ALTER COLUMN link_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.link_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matches (
    match_id bigint NOT NULL,
    certification_score real NOT NULL,
    education_score real NOT NULL,
    experience_score real NOT NULL,
    final_score real NOT NULL,
    justification text,
    language_score real NOT NULL,
    skills_score real NOT NULL,
    job_offer_id bigint NOT NULL,
    resume_id bigint NOT NULL
);


ALTER TABLE public.matches OWNER TO postgres;

--
-- Name: matches_match_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matches ALTER COLUMN match_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matches_match_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_result_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_result_messages (
    message_result_id bigint NOT NULL,
    message character varying(255)
);


ALTER TABLE public.message_result_messages OWNER TO postgres;

--
-- Name: message_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_results (
    id bigint NOT NULL,
    employee_id bigint,
    prediction_score double precision
);


ALTER TABLE public.message_results OWNER TO postgres;

--
-- Name: message_results_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(255),
    read boolean NOT NULL,
    user_id bigint
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.offers (
    id bigint NOT NULL,
    expiration_date date,
    job_title character varying(255),
    number_of_pos integer,
    project_or_client character varying(255),
    publish_date date,
    published boolean NOT NULL,
    reference character varying(255),
    request_date date,
    salary real,
    sections jsonb DEFAULT '{}'::jsonb NOT NULL,
    starting_date date,
    creation_date date,
    cur_status character varying(255) DEFAULT 'Draft',
    years_of_exp integer,
    contract_type_id bigint,
    created_by_id bigint,
    currency_id bigint,
    department_id bigint,
    diploma_type_id bigint,
    work_mode_id bigint
    
);


ALTER TABLE public.offers OWNER TO postgres;

--
-- Name: offers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: other_information; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.other_information (
    id integer NOT NULL,
    bank_domiciliation boolean NOT NULL,
    mariage_date timestamp(6) without time zone,
    stc_servi boolean NOT NULL,
    employe_id bigint
);


ALTER TABLE public.other_information OWNER TO postgres;

--
-- Name: other_information_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.other_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.other_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phase (
    phase_id bigint NOT NULL,
    description character varying(1000),
    end_date character varying(255),
    name character varying(255),
    started_date character varying(255),
    total_hours integer NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.phase OWNER TO postgres;

--
-- Name: phase_phase_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.phase ALTER COLUMN phase_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phase_phase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photo (
    id bigint NOT NULL,
    data oid NOT NULL,
    file_name character varying(255) NOT NULL,
    file_type character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.photo OWNER TO postgres;

--
-- Name: photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prediction_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prediction_item (
    id bigint NOT NULL,
    analyzed_at timestamp(6) without time zone,
    emotion character varying(255),
    employee_id character varying(255),
    employee_name character varying(255),
    general_emotion character varying(255),
    general_topic character varying(255),
    id_test character varying(255),
    message character varying(255),
    sentiment character varying(255),
    topic character varying(255),
    prediction_result_id bigint
);


ALTER TABLE public.prediction_item OWNER TO postgres;

--
-- Name: prediction_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prediction_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prediction_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prediction_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prediction_result (
    id bigint NOT NULL,
    analyzed_at timestamp(6) without time zone,
    employee_name character varying(255)
);


ALTER TABLE public.prediction_result OWNER TO postgres;

--
-- Name: prediction_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prediction_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prediction_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project (
    project_id bigint NOT NULL,
    end_date character varying(255),
    name character varying(255),
    started_date character varying(255),
    total_hours integer NOT NULL,
    client_id bigint
);


ALTER TABLE public.project OWNER TO postgres;

--
-- Name: project_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project ALTER COLUMN project_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    question_id bigint NOT NULL,
    question_text character varying(255),
    question_type character varying(255),
    theme character varying(255),
    weight double precision,
    questionnaire_id bigint,
    scale_max integer,
    CONSTRAINT question_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['CHOICE'::character varying, 'TEXT'::character varying])::text[])))
);


ALTER TABLE public.question OWNER TO postgres;

--
-- Name: question_likert_labels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_likert_labels (
    question_question_id bigint NOT NULL,
    likert_labels character varying(255),
    likert_labels_key character varying(255) NOT NULL
);


ALTER TABLE public.question_likert_labels OWNER TO postgres;

--
-- Name: question_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questionnaire; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaire (
    questionnaire_id bigint NOT NULL,
    description character varying(255),
    title character varying(255)
);


ALTER TABLE public.questionnaire OWNER TO postgres;

--
-- Name: questionnaire_questionnaire_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questionnaire ALTER COLUMN questionnaire_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questionnaire_questionnaire_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questionnaire_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaire_users (
    questionnaire_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.questionnaire_users OWNER TO postgres;

--
-- Name: recommendation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recommendation (
    rec_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    reason character varying(255),
    recommendation character varying(255),
    severity_level character varying(255),
    source_message_id integer,
    visibility character varying(255)
);


ALTER TABLE public.recommendation OWNER TO postgres;

--
-- Name: recommendation_rec_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recommendation ALTER COLUMN rec_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_rec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: response_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.response_questions (
    response_id bigint NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.response_questions OWNER TO postgres;

--
-- Name: resume; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resume (
    resume_id bigint NOT NULL,
    address text,
    email character varying(255) NOT NULL,
    linkedin character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    years_of_experience real
);


ALTER TABLE public.resume OWNER TO postgres;

--
-- Name: resume_resume_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resume ALTER COLUMN resume_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_resume_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    name character varying(255),
    site_id bigint NOT NULL
);


ALTER TABLE public.room OWNER TO postgres;

--
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: self_training_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.self_training_employee (
    self_training_id bigint NOT NULL,
    employee_id bigint,
    plan_id bigint
);


ALTER TABLE public.self_training_employee OWNER TO postgres;

--
-- Name: self_training_employee_self_training_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.self_training_employee ALTER COLUMN self_training_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.self_training_employee_self_training_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: self_training_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.self_training_session (
    self_training_session_id bigint NOT NULL,
    priority character varying(255),
    priority_justification text,
    skills_justification text,
    training_justification text,
    training_title character varying(255),
    self_training_id bigint
);


ALTER TABLE public.self_training_session OWNER TO postgres;

--
-- Name: self_training_session_self_training_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.self_training_session ALTER COLUMN self_training_session_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.self_training_session_self_training_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.site (
    site_id bigint NOT NULL,
    site_name character varying(255)
);


ALTER TABLE public.site OWNER TO postgres;

--
-- Name: site_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.site ALTER COLUMN site_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skill (
    skill_id bigint NOT NULL,
    skill_name character varying(255) NOT NULL,
    resume_id bigint NOT NULL
);


ALTER TABLE public.skill OWNER TO postgres;

--
-- Name: skill_skill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.skill ALTER COLUMN skill_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: structured_training_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.structured_training_session (
    id bigint NOT NULL,
    priority character varying(255),
    priority_justification text,
    training_justification text,
    training_title character varying(255),
    training_recommendation_plan_id bigint,
    skills_justification text
);


ALTER TABLE public.structured_training_session OWNER TO postgres;

--
-- Name: structured_training_session_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.structured_training_session_employee (
    structured_training_session_id bigint NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.structured_training_session_employee OWNER TO postgres;

--
-- Name: structured_training_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.structured_training_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.structured_training_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_response; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_response (
    response_id bigint NOT NULL,
    answer_value character varying(255),
    date character varying(255),
    user_id bigint
);


ALTER TABLE public.survey_response OWNER TO postgres;

--
-- Name: survey_response_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.survey_response ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_response_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task (
    task_id bigint NOT NULL,
    actual_time integer NOT NULL,
    created_date timestamp(6) without time zone,
    description character varying(2000),
    due_date character varying(255),
    estimated_time integer NOT NULL,
    name character varying(255),
    priority character varying(255),
    status character varying(255),
    updated_by character varying(255),
    updated_date timestamp(6) without time zone,
    assignee_id bigint,
    parent_task_id bigint,
    phase_id bigint,
    reporter_id bigint,
    jira_key character varying(255),
    project_id bigint,
    CONSTRAINT task_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'BLOCKER'::character varying])::text[]))),
    CONSTRAINT task_status_check CHECK (((status)::text = ANY ((ARRAY['TO_DO'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.task OWNER TO postgres;

--
-- Name: task_labels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.task_labels (
    task_task_id bigint NOT NULL,
    labels character varying(255)
);


ALTER TABLE public.task_labels OWNER TO postgres;

--
-- Name: task_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.task ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_recommendation_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.training_recommendation_plan (
    plan_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255),
    requester_id bigint
);


ALTER TABLE public.training_recommendation_plan OWNER TO postgres;

--
-- Name: training_recommendation_plan_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.training_recommendation_plan ALTER COLUMN plan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_recommendation_plan_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_mode; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.work_mode (
    id_work_mode bigint NOT NULL,
    work_mode_name character varying(255)
);


ALTER TABLE public.work_mode OWNER TO postgres;

--
-- Name: work_mode_id_work_mode_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.work_mode ALTER COLUMN id_work_mode ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_mode_id_work_mode_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_job_offer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workflow_job_offer (
    id bigint NOT NULL,
    is_completed boolean DEFAULT false NOT NULL,
    is_published boolean DEFAULT false NOT NULL,
    process_instance_id character varying(255) NOT NULL,
    status_job_offer character varying(255),
    job_offer_id bigint NOT NULL,
    complete_date timestamp(6) without time zone,
    completed boolean DEFAULT false NOT NULL,
    published boolean DEFAULT false NOT NULL,
    publish_date timestamp(6) without time zone
);


ALTER TABLE public.workflow_job_offer OWNER TO postgres;

--
-- Name: workflow_job_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workflow_job_offer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_job_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_leave; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workflow_leave (
    id bigint NOT NULL,
    proc_inst_id character varying(255),
    status_leave character varying(255)
);


ALTER TABLE public.workflow_leave OWNER TO postgres;

--
-- Name: workflow_leave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workflow_leave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_leave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: year_evaluation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.year_evaluation (
    id_year_evaluation integer NOT NULL,
    date timestamp(6) without time zone,
    note character varying(255),
    employe_id bigint
);


ALTER TABLE public.year_evaluation OWNER TO postgres;

--
-- Name: year_evaluation_id_year_evaluation_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.year_evaluation ALTER COLUMN id_year_evaluation ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.year_evaluation_id_year_evaluation_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analyse_message analyse_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analyse_message
    ADD CONSTRAINT analyse_message_pkey PRIMARY KEY (id);


--
-- Name: analysis_result analysis_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analysis_result
    ADD CONSTRAINT analysis_result_pkey PRIMARY KEY (id);


--
-- Name: answer answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (application_id);


--
-- Name: career_path_need_company career_path_need_company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_path_need_company
    ADD CONSTRAINT career_path_need_company_pkey PRIMARY KEY (id);


--
-- Name: career_pathing_recommendation_employee career_pathing_recommendation_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation_employee
    ADD CONSTRAINT career_pathing_recommendation_employee_pkey PRIMARY KEY (id);


--
-- Name: career_pathing_recommendation career_pathing_recommendation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation
    ADD CONSTRAINT career_pathing_recommendation_pkey PRIMARY KEY (id);


--
-- Name: career_pathing_recommendation_plan career_pathing_recommendation_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation_plan
    ADD CONSTRAINT career_pathing_recommendation_plan_pkey PRIMARY KEY (id);


--
-- Name: career_pathing_skill career_pathing_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_skill
    ADD CONSTRAINT career_pathing_skill_pkey PRIMARY KEY (id);


--
-- Name: certification certification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certification
    ADD CONSTRAINT certification_pkey PRIMARY KEY (certification_id);


--
-- Name: channel channel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channel
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);


--
-- Name: choice choice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.choice
    ADD CONSTRAINT choice_pkey PRIMARY KEY (id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (client_id);


--
-- Name: coaching_session coaching_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coaching_session
    ADD CONSTRAINT coaching_session_pkey PRIMARY KEY (id);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (comment_id);


--
-- Name: contract_type contract_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contract_type
    ADD CONSTRAINT contract_type_pkey PRIMARY KEY (id);


--
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id_currency);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- Name: diploma diploma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diploma
    ADD CONSTRAINT diploma_pkey PRIMARY KEY (id_diplome);


--
-- Name: diploma_type diploma_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diploma_type
    ADD CONSTRAINT diploma_type_pkey PRIMARY KEY (id_diploma_type);


--
-- Name: education education_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education
    ADD CONSTRAINT education_pkey PRIMARY KEY (education_id);


--
-- Name: employe employe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT employe_pkey PRIMARY KEY (id);


--
-- Name: employee_insight employee_insight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_insight
    ADD CONSTRAINT employee_insight_pkey PRIMARY KEY (employee_insight_id);


--
-- Name: employee_skills employee_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_skills
    ADD CONSTRAINT employee_skills_pkey PRIMARY KEY (id);


--
-- Name: experience experience_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experience
    ADD CONSTRAINT experience_pkey PRIMARY KEY (experience_id);


--
-- Name: global_insight global_insight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_insight
    ADD CONSTRAINT global_insight_pkey PRIMARY KEY (global_insight_id);


--
-- Name: history_workflow_leave history_workflow_leave_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.history_workflow_leave
    ADD CONSTRAINT history_workflow_leave_pkey PRIMARY KEY (history_workflow_leave_id);


--
-- Name: imputation imputation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT imputation_pkey PRIMARY KEY (imputation_id);


--
-- Name: insurance insurance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.insurance
    ADD CONSTRAINT insurance_pkey PRIMARY KEY (id);


--
-- Name: interview interview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT interview_pkey PRIMARY KEY (interview_id);


--
-- Name: language language_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT language_pkey PRIMARY KEY (language_id);


--
-- Name: leave_request leave_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_pkey PRIMARY KEY (id);


--
-- Name: leave_sold leave_sold_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_sold
    ADD CONSTRAINT leave_sold_pkey PRIMARY KEY (id_leave_sold);


--
-- Name: leave_type leave_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_type
    ADD CONSTRAINT leave_type_pkey PRIMARY KEY (id_leave_type);


--
-- Name: link link_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT link_pkey PRIMARY KEY (link_id);


--
-- Name: matches matches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT matches_pkey PRIMARY KEY (match_id);


--
-- Name: message_results message_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_results
    ADD CONSTRAINT message_results_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: other_information other_information_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.other_information
    ADD CONSTRAINT other_information_pkey PRIMARY KEY (id);


--
-- Name: phase phase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase
    ADD CONSTRAINT phase_pkey PRIMARY KEY (phase_id);


--
-- Name: photo photo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT photo_pkey PRIMARY KEY (id);


--
-- Name: prediction_item prediction_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prediction_item
    ADD CONSTRAINT prediction_item_pkey PRIMARY KEY (id);


--
-- Name: prediction_result prediction_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prediction_result
    ADD CONSTRAINT prediction_result_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (project_id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (question_id);


--
-- Name: questionnaire questionnaire_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire
    ADD CONSTRAINT questionnaire_pkey PRIMARY KEY (questionnaire_id);


--
-- Name: recommendation recommendation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendation
    ADD CONSTRAINT recommendation_pkey PRIMARY KEY (rec_id);


--
-- Name: resume resume_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resume
    ADD CONSTRAINT resume_pkey PRIMARY KEY (resume_id);


--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- Name: self_training_employee self_training_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.self_training_employee
    ADD CONSTRAINT self_training_employee_pkey PRIMARY KEY (self_training_id);


--
-- Name: self_training_session self_training_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.self_training_session
    ADD CONSTRAINT self_training_session_pkey PRIMARY KEY (self_training_session_id);


--
-- Name: site site_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.site
    ADD CONSTRAINT site_pkey PRIMARY KEY (site_id);


--
-- Name: skill skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill
    ADD CONSTRAINT skill_pkey PRIMARY KEY (skill_id);


--
-- Name: structured_training_session structured_training_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.structured_training_session
    ADD CONSTRAINT structured_training_session_pkey PRIMARY KEY (id);


--
-- Name: survey_response survey_response_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_response
    ADD CONSTRAINT survey_response_pkey PRIMARY KEY (response_id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (task_id);


--
-- Name: training_recommendation_plan training_recommendation_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_recommendation_plan
    ADD CONSTRAINT training_recommendation_plan_pkey PRIMARY KEY (plan_id);


--
-- Name: app_user uk1j9d9a06i600gd43uu3km82jw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email);


--
-- Name: application uk4dqnytodywd0dyr87qivd5a2w; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT uk4dqnytodywd0dyr87qivd5a2w UNIQUE (match_id);


--
-- Name: leave_type uk61qanpjyq3t0h6i1xaqbb64b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_type
    ADD CONSTRAINT uk61qanpjyq3t0h6i1xaqbb64b UNIQUE (type);


--
-- Name: analysis_result uk7yujoorufi12ree3eamslkm3p; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analysis_result
    ADD CONSTRAINT uk7yujoorufi12ree3eamslkm3p UNIQUE (employee_id, questionnaire_id);


--
-- Name: workflow_leave ukc0qgf227bxpake2130iui4mph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_leave
    ADD CONSTRAINT ukc0qgf227bxpake2130iui4mph UNIQUE (proc_inst_id);


--
-- Name: other_information ukenylpeg5mucgl1am6xo2ai98l; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.other_information
    ADD CONSTRAINT ukenylpeg5mucgl1am6xo2ai98l UNIQUE (employe_id);


--
-- Name: photo ukhd8tpnuep2a8ert8ue5u4sgir; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT ukhd8tpnuep2a8ert8ue5u4sgir UNIQUE (user_id);


--
-- Name: global_insight_employees uko3wxsi4b2ha3yktw5ytbj0kfy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_insight_employees
    ADD CONSTRAINT uko3wxsi4b2ha3yktw5ytbj0kfy UNIQUE (employees_employee_insight_id);


--
-- Name: app_user ukoum85vbcbyp5xrql26rajht02; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT ukoum85vbcbyp5xrql26rajht02 UNIQUE (cin);


--
-- Name: leave_request ukp9hlog0oqwly5bee3wx2vqnhq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT ukp9hlog0oqwly5bee3wx2vqnhq UNIQUE (workflow_leave_id);


--
-- Name: workflow_job_offer ukpk93pevgl3c0l5dbs0gl2homh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_job_offer
    ADD CONSTRAINT ukpk93pevgl3c0l5dbs0gl2homh UNIQUE (job_offer_id);


--
-- Name: work_mode work_mode_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_mode
    ADD CONSTRAINT work_mode_pkey PRIMARY KEY (id_work_mode);


--
-- Name: workflow_job_offer workflow_job_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_job_offer
    ADD CONSTRAINT workflow_job_offer_pkey PRIMARY KEY (id);


--
-- Name: workflow_leave workflow_leave_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_leave
    ADD CONSTRAINT workflow_leave_pkey PRIMARY KEY (id);


--
-- Name: year_evaluation year_evaluation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.year_evaluation
    ADD CONSTRAINT year_evaluation_pkey PRIMARY KEY (id_year_evaluation);


--
-- Name: career_pathing_recommendation_employee fk11i4169nlqg9e1kvbobwx5rc7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation_employee
    ADD CONSTRAINT fk11i4169nlqg9e1kvbobwx5rc7 FOREIGN KEY (recommendation_id) REFERENCES public.career_pathing_recommendation_plan(id);


--
-- Name: offers fk167d9gose7q8uf44sonrwvl5p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk167d9gose7q8uf44sonrwvl5p FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: message_result_messages fk1krxvhml0w3wd98chpa05s1qe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message_result_messages
    ADD CONSTRAINT fk1krxvhml0w3wd98chpa05s1qe FOREIGN KEY (message_result_id) REFERENCES public.message_results(id);


--
-- Name: application fk1l7lh9cf5rwfbfiln6ufoap58; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fk1l7lh9cf5rwfbfiln6ufoap58 FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: imputation fk23ixx3b1cudsu5yajsrdj5qv8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT fk23ixx3b1cudsu5yajsrdj5qv8 FOREIGN KEY (task_id) REFERENCES public.task(task_id);


--
-- Name: matches fk24vm0ojlsoxww81hwv9ulklvn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fk24vm0ojlsoxww81hwv9ulklvn FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: included_skill_structured_training fk29wpcvwisk7q7j1cn5tdqifne; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.included_skill_structured_training
    ADD CONSTRAINT fk29wpcvwisk7q7j1cn5tdqifne FOREIGN KEY (structured_training_session_id) REFERENCES public.structured_training_session(id);


--
-- Name: leave_sold fk2hguydvb7m8wtdthf0ncgwcy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_sold
    ADD CONSTRAINT fk2hguydvb7m8wtdthf0ncgwcy FOREIGN KEY (leave_type_id) REFERENCES public.leave_type(id_leave_type);


--
-- Name: offers fk2rsc97j6rxli6u4g5wu0r7sb0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk2rsc97j6rxli6u4g5wu0r7sb0 FOREIGN KEY (contract_type_id) REFERENCES public.contract_type(id);


--
-- Name: self_training_session fk2u8k67lgvjgfbuckesmt673mi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.self_training_session
    ADD CONSTRAINT fk2u8k67lgvjgfbuckesmt673mi FOREIGN KEY (self_training_id) REFERENCES public.self_training_employee(self_training_id);


--
-- Name: offers fk3dykm03hhtlcexjxn0m2f9iog; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk3dykm03hhtlcexjxn0m2f9iog FOREIGN KEY (currency_id) REFERENCES public.currency(id_currency);


--
-- Name: question_likert_labels fk3ewvg9h1d8sk4tmvj4vqoxk6a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_likert_labels
    ADD CONSTRAINT fk3ewvg9h1d8sk4tmvj4vqoxk6a FOREIGN KEY (question_question_id) REFERENCES public.question(question_id);


--
-- Name: certification fk3ptoo42u18x4smfpahluk73bi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certification
    ADD CONSTRAINT fk3ptoo42u18x4smfpahluk73bi FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: room fk3vbvvnfsoaa2iesq5qb1uwtkq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fk3vbvvnfsoaa2iesq5qb1uwtkq FOREIGN KEY (site_id) REFERENCES public.site(site_id);


--
-- Name: question fk5a4p6bl440c9amsq08rs546wu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk5a4p6bl440c9amsq08rs546wu FOREIGN KEY (questionnaire_id) REFERENCES public.questionnaire(questionnaire_id);


--
-- Name: coaching_session_employee fk5fu8s85krn72bhy2a88xrrgfb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coaching_session_employee
    ADD CONSTRAINT fk5fu8s85krn72bhy2a88xrrgfb FOREIGN KEY (coaching_session_id) REFERENCES public.coaching_session(id);


--
-- Name: application fk6sshcxm8kwjy2hhqkrtrvhxph; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fk6sshcxm8kwjy2hhqkrtrvhxph FOREIGN KEY (job_offer_id) REFERENCES public.offers(id);


--
-- Name: prediction_item fk79ivxj6qa3yn5rwvgagka3pfa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prediction_item
    ADD CONSTRAINT fk79ivxj6qa3yn5rwvgagka3pfa FOREIGN KEY (prediction_result_id) REFERENCES public.prediction_result(id);


--
-- Name: history_workflow_leave fk7ff4huuqy5mbagvxbx1v1k201; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.history_workflow_leave
    ADD CONSTRAINT fk7ff4huuqy5mbagvxbx1v1k201 FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: leave_request fk7nc4hxm1gc3ud3kq7612sgleg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT fk7nc4hxm1gc3ud3kq7612sgleg FOREIGN KEY (leave_type) REFERENCES public.leave_type(id_leave_type);


--
-- Name: leave_request fk7ygnlapmt8oh9bbi3g6p9kjkw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT fk7ygnlapmt8oh9bbi3g6p9kjkw FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: answer fk8frr4bcabmmeyyu60qt7iiblo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fk8frr4bcabmmeyyu60qt7iiblo FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: project fk8nw995uro0115f1go0dmrtn2d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fk8nw995uro0115f1go0dmrtn2d FOREIGN KEY (client_id) REFERENCES public.client(client_id);


--
-- Name: link fk8sav5e8j658qaludbauvav70k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT fk8sav5e8j658qaludbauvav70k FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: task fk8xyblymf28bn7oll2iwn04d88; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fk8xyblymf28bn7oll2iwn04d88 FOREIGN KEY (reporter_id) REFERENCES public.app_user(id);


--
-- Name: offers fk9cf4f7d5qrtff3shyoqjuy59u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fk9cf4f7d5qrtff3shyoqjuy59u FOREIGN KEY (diploma_type_id) REFERENCES public.diploma_type(id_diploma_type);


--
-- Name: coaching_session fk9g8ptr4c5uv292flg16stmk6l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coaching_session
    ADD CONSTRAINT fk9g8ptr4c5uv292flg16stmk6l FOREIGN KEY (coach_id) REFERENCES public.employe(id);


--
-- Name: questionnaire_users fka9a6bixhnhyfd589mtla9phh6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire_users
    ADD CONSTRAINT fka9a6bixhnhyfd589mtla9phh6 FOREIGN KEY (questionnaire_id) REFERENCES public.questionnaire(questionnaire_id);


--
-- Name: employee_skills fkaeu26l5b2lgf3ia5lmdnyova8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_skills
    ADD CONSTRAINT fkaeu26l5b2lgf3ia5lmdnyova8 FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: career_pathing_recommendation fkah08981xltxvt6iiya0dva1v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation
    ADD CONSTRAINT fkah08981xltxvt6iiya0dva1v FOREIGN KEY (employee_id) REFERENCES public.career_pathing_recommendation_employee(id);


--
-- Name: skill fkahgxm3rt1nahhdy66taa4xjrv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill
    ADD CONSTRAINT fkahgxm3rt1nahhdy66taa4xjrv FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: answer fkb29pf3a27gidf0ryrxqkott3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fkb29pf3a27gidf0ryrxqkott3f FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: career_pathing_recommendation_plan fkb4o4kb1s5pokj16vmbc3q0sfw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation_plan
    ADD CONSTRAINT fkb4o4kb1s5pokj16vmbc3q0sfw FOREIGN KEY (requester_id) REFERENCES public.employe(id);


--
-- Name: task fkbmlrl2jnd3vcqmt3m8sh84ukm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkbmlrl2jnd3vcqmt3m8sh84ukm FOREIGN KEY (assignee_id) REFERENCES public.app_user(id);


--
-- Name: choice fkcaq6r76cswke5b9fk6fyx3y5w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.choice
    ADD CONSTRAINT fkcaq6r76cswke5b9fk6fyx3y5w FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: included_skill_coaching fkcqqbuaourprdgbuhfwaqxf37h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.included_skill_coaching
    ADD CONSTRAINT fkcqqbuaourprdgbuhfwaqxf37h FOREIGN KEY (coaching_session_id) REFERENCES public.coaching_session(id);


--
-- Name: response_questions fkdfvtr116m95dgpdrrwkts5gbs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.response_questions
    ADD CONSTRAINT fkdfvtr116m95dgpdrrwkts5gbs FOREIGN KEY (question_id) REFERENCES public.question(question_id);


--
-- Name: interview fkdyrt85lva791fmh1qnhf0ee0f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT fkdyrt85lva791fmh1qnhf0ee0f FOREIGN KEY (application_id) REFERENCES public.application(application_id);


--
-- Name: phase fke7vf02rk1qw3jd8p8qol3whf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phase
    ADD CONSTRAINT fke7vf02rk1qw3jd8p8qol3whf FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: self_training_employee fkeguei4pfan6cght58qtvt2f7j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.self_training_employee
    ADD CONSTRAINT fkeguei4pfan6cght58qtvt2f7j FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: language fkelmqibroy3878w1x29pipkway; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language
    ADD CONSTRAINT fkelmqibroy3878w1x29pipkway FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: comment fkemqjawvkiyejurssvwm5c21y7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkemqjawvkiyejurssvwm5c21y7 FOREIGN KEY (author_id) REFERENCES public.app_user(id);


--
-- Name: employe fken11ygfa2ms86ydd8ydi8yug1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fken11ygfa2ms86ydd8ydi8yug1 FOREIGN KEY (id) REFERENCES public.app_user(id);


--
-- Name: response_questions fkeqfpxh3aeghpyt6f77eoxvaux; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.response_questions
    ADD CONSTRAINT fkeqfpxh3aeghpyt6f77eoxvaux FOREIGN KEY (response_id) REFERENCES public.survey_response(response_id);


--
-- Name: interview_interviewers fkf9qu4ig4v12f2gd00s56xu3iq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_interviewers
    ADD CONSTRAINT fkf9qu4ig4v12f2gd00s56xu3iq FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: comment fkfknte4fhjhet3l1802m1yqa50; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkfknte4fhjhet3l1802m1yqa50 FOREIGN KEY (task_id) REFERENCES public.task(task_id);


--
-- Name: employee_insight fkg32125c2lgisddy5x9h3amkc5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_insight
    ADD CONSTRAINT fkg32125c2lgisddy5x9h3amkc5 FOREIGN KEY (user_id) REFERENCES public.employe(id);


--
-- Name: structured_training_session fkg3ybun5nw19sd018bkhi8ky8b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.structured_training_session
    ADD CONSTRAINT fkg3ybun5nw19sd018bkhi8ky8b FOREIGN KEY (training_recommendation_plan_id) REFERENCES public.training_recommendation_plan(plan_id);


--
-- Name: photo fkgb5hw1bby38s1qq9q7sn4pgjj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT fkgb5hw1bby38s1qq9q7sn4pgjj FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- Name: training_recommendation_plan fkgnprhoj152xwrfefwnjvvhtof; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.training_recommendation_plan
    ADD CONSTRAINT fkgnprhoj152xwrfefwnjvvhtof FOREIGN KEY (requester_id) REFERENCES public.employe(id);


--
-- Name: career_pathing_skill fkgppmah9njyh6vo9ovyyh8i90s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_skill
    ADD CONSTRAINT fkgppmah9njyh6vo9ovyyh8i90s FOREIGN KEY (job_id) REFERENCES public.career_pathing_recommendation(id);


--
-- Name: offers fkhgy48w5w790f35mx04k9o2ltg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fkhgy48w5w790f35mx04k9o2ltg FOREIGN KEY (work_mode_id) REFERENCES public.work_mode(id_work_mode);


--
-- Name: leave_sold fki00e5s176dd6ug073eyrsqlnr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_sold
    ADD CONSTRAINT fki00e5s176dd6ug073eyrsqlnr FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: included_skill_self_training fki824f89ejssndwueevqqiqqoq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.included_skill_self_training
    ADD CONSTRAINT fki824f89ejssndwueevqqiqqoq FOREIGN KEY (self_training_session_id) REFERENCES public.self_training_session(self_training_session_id);


--
-- Name: coaching_session_employee fkie0sjglx0dovcg4krgs0cc81u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coaching_session_employee
    ADD CONSTRAINT fkie0sjglx0dovcg4krgs0cc81u FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: global_insight_employees fkjiwfqu5nxjkj4a9997r4mywyj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_insight_employees
    ADD CONSTRAINT fkjiwfqu5nxjkj4a9997r4mywyj FOREIGN KEY (global_insight_global_insight_id) REFERENCES public.global_insight(global_insight_id);


--
-- Name: education fkjyor7xegks1vh01tajsof6gb4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education
    ADD CONSTRAINT fkjyor7xegks1vh01tajsof6gb4 FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: task fkk8qrwowg31kx7hp93sru1pdqa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkk8qrwowg31kx7hp93sru1pdqa FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: workflow_job_offer fkkg4f2laal417n79wjx6swl54x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_job_offer
    ADD CONSTRAINT fkkg4f2laal417n79wjx6swl54x FOREIGN KEY (job_offer_id) REFERENCES public.offers(id);


--
-- Name: experience fkkm7wjycrf87ube2yf3puyqsdu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experience
    ADD CONSTRAINT fkkm7wjycrf87ube2yf3puyqsdu FOREIGN KEY (resume_id) REFERENCES public.resume(resume_id);


--
-- Name: interview fkljrjnehxnuj9rclc773yaeeh7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview
    ADD CONSTRAINT fkljrjnehxnuj9rclc773yaeeh7 FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- Name: application fkll6x5sqcwdu1qhcip0g9ylg54; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fkll6x5sqcwdu1qhcip0g9ylg54 FOREIGN KEY (match_id) REFERENCES public.matches(match_id);


--
-- Name: imputation fkln2tsy90cbmy1uqh1k4p8v19o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imputation
    ADD CONSTRAINT fkln2tsy90cbmy1uqh1k4p8v19o FOREIGN KEY (user_id) REFERENCES public.employe(id);


--
-- Name: employe fklnt9tuv2fky0q9ighk6fkx13j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fklnt9tuv2fky0q9ighk6fkx13j FOREIGN KEY (contract_type_id) REFERENCES public.contract_type(id) ON DELETE SET NULL;


--
-- Name: global_insight_employees fkm2ftw905xpttkjn8ljtruq23y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.global_insight_employees
    ADD CONSTRAINT fkm2ftw905xpttkjn8ljtruq23y FOREIGN KEY (employees_employee_insight_id) REFERENCES public.employee_insight(employee_insight_id);


--
-- Name: answer fkm2k7pkvxup1ecwhn0fruwyeuc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT fkm2k7pkvxup1ecwhn0fruwyeuc FOREIGN KEY (questionnaire_id) REFERENCES public.questionnaire(questionnaire_id);


--
-- Name: task_labels fkmig6c5qhl7skvse82hbtlj47k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task_labels
    ADD CONSTRAINT fkmig6c5qhl7skvse82hbtlj47k FOREIGN KEY (task_task_id) REFERENCES public.task(task_id);


--
-- Name: matches fkmpkqowvt3wivmcyu7y9ud6yp8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matches
    ADD CONSTRAINT fkmpkqowvt3wivmcyu7y9ud6yp8 FOREIGN KEY (job_offer_id) REFERENCES public.offers(id);


--
-- Name: leave_request fkn46x4x0hsy23nxbhfoio922mo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT fkn46x4x0hsy23nxbhfoio922mo FOREIGN KEY (workflow_leave_id) REFERENCES public.workflow_leave(id);


--
-- Name: diploma fkn5q2it86fusm7ddmeo30so8e7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diploma
    ADD CONSTRAINT fkn5q2it86fusm7ddmeo30so8e7 FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: coaching_session fknprgbb9ufhf3enokvlaf5bsrd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coaching_session
    ADD CONSTRAINT fknprgbb9ufhf3enokvlaf5bsrd FOREIGN KEY (training_recommendation_plan_id) REFERENCES public.training_recommendation_plan(plan_id);


--
-- Name: structured_training_session_employee fko1omnihu21jhdyl85axlgvl40; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.structured_training_session_employee
    ADD CONSTRAINT fko1omnihu21jhdyl85axlgvl40 FOREIGN KEY (structured_training_session_id) REFERENCES public.structured_training_session(id);


--
-- Name: structured_training_session_employee fko596wn5xdlerjshcjfiugr448; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.structured_training_session_employee
    ADD CONSTRAINT fko596wn5xdlerjshcjfiugr448 FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: offers fkoh4o6yac1cidkmgff875l71ft; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT fkoh4o6yac1cidkmgff875l71ft FOREIGN KEY (created_by_id) REFERENCES public.employe(id);


--
-- Name: analyse_message fkp28xi44g5la6v9ryfnvo4su7n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analyse_message
    ADD CONSTRAINT fkp28xi44g5la6v9ryfnvo4su7n FOREIGN KEY (message_result_id) REFERENCES public.message_results(id);


--
-- Name: employe fkp3oejde2sengmvnqtrdd7o895; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkp3oejde2sengmvnqtrdd7o895 FOREIGN KEY (parent_id) REFERENCES public.insurance(id);


--
-- Name: employe fkpjypnh0xgemw97pg8ncldsvxd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkpjypnh0xgemw97pg8ncldsvxd FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: survey_response fkq0y23kp66lujkybhqo4pg4yed; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_response
    ADD CONSTRAINT fkq0y23kp66lujkybhqo4pg4yed FOREIGN KEY (user_id) REFERENCES public.employe(id);


--
-- Name: interview_interviewers fkqkw494hubriemxli1ly58fcsr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interview_interviewers
    ADD CONSTRAINT fkqkw494hubriemxli1ly58fcsr FOREIGN KEY (interview_id) REFERENCES public.interview(interview_id);


--
-- Name: year_evaluation fkqvattdab4g4t1ct1pqgy757mc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.year_evaluation
    ADD CONSTRAINT fkqvattdab4g4t1ct1pqgy757mc FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: task fkqxs9fnf0nvg4pou1gng0jtom4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkqxs9fnf0nvg4pou1gng0jtom4 FOREIGN KEY (parent_task_id) REFERENCES public.task(task_id);


--
-- Name: task fkrhtmkhvtfsd7bl6jwdex9uh6b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkrhtmkhvtfsd7bl6jwdex9uh6b FOREIGN KEY (phase_id) REFERENCES public.phase(phase_id);


--
-- Name: self_training_employee fkrvgu1d2k0tffk68ggh0opcinx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.self_training_employee
    ADD CONSTRAINT fkrvgu1d2k0tffk68ggh0opcinx FOREIGN KEY (plan_id) REFERENCES public.training_recommendation_plan(plan_id);


--
-- Name: questionnaire_users fkrxnp0c2kc21ivru9n8rkemi2k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire_users
    ADD CONSTRAINT fkrxnp0c2kc21ivru9n8rkemi2k FOREIGN KEY (user_id) REFERENCES public.employe(id);


--
-- Name: career_pathing_recommendation_employee fksiyc31k7chgdumrv9r5btn27t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.career_pathing_recommendation_employee
    ADD CONSTRAINT fksiyc31k7chgdumrv9r5btn27t FOREIGN KEY (employee_id) REFERENCES public.employe(id);


--
-- Name: other_information fkt9jikl52gpoe318fuu187t0pf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.other_information
    ADD CONSTRAINT fkt9jikl52gpoe318fuu187t0pf FOREIGN KEY (employe_id) REFERENCES public.employe(id);


--
-- Name: employe fkteic6gyam4fsbslvn6k0736qw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employe
    ADD CONSTRAINT fkteic6gyam4fsbslvn6k0736qw FOREIGN KEY (manager_id) REFERENCES public.employe(id);


--
-- PostgreSQL database dump complete
--
